apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-simulation-deployment
  labels:
    app: ms-simulation-deployment
spec:
  selector:
    matchLabels:
      app: ms-simulation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-simulation-deployment
    spec:
      containers:
        - name: ms-simulation
          image: vicentearce/ms-simulation
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_SIMULATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_SIMULATION
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_SIMULATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD